set THREADS_STREAM=0
set ASYNC_WEB=0
set MODEL_NAME=yolo5
set MODEL_BEST=yolo5m.pt
set STREAM_SRC=rtsp://admin:admin@80.252.145.203:554/live/main
set FRAME_RATE=25
set APP_PORT=5000
set TEMPLATE_FOLDER=..\..\front\demo
set STATIC_FOLDER=..\..\front\demo
set STATIC_URL_PATH=/demo/
start microsoft-edge:http://localhost:%APP_PORT%/flow/test/
venv\Scripts\python back